### ISSUE TITLE
Convert .html to .md ?

### ISSUE THREAD

**Issue by davidmiller** [nhshackday/nhshackday.github.io#104]
Suggest it would lower the barrier to pull requests on content if we could have content as markdown.

e.g. ideally #103 would have been an edit to http://prose.io/#nhshackday/nhshackday.github.io/edit/master/index.html rather than an issue.

It's an enabler.

Thoughts?

**Comment by DeckOfPandas** [comment]
There's no page container on the pages for datasets/apis or organiser notes, but I can't make <div> play nice in markdown. Helllp?

**Comment by DeckOfPandas** [comment]
Double plus from me

Will attend to it

**Comment by blu3id** [comment]
Mostly addressed by #236 page that should be edited by anyone are .md ones that need thought and understanding of html are .html
