### ISSUE TITLE
Need header image for Cardiff..

### ISSUE THREAD

**Issue by rossjones** [nhshackday/nhshackday.github.io#162]
Something nice like https://www.flickr.com/photos/ricklees/14739870211/in/photolist-osvFTi-8VSBjA-8NSyep-BzT1d-rC18-9AHtV5-BzSXB-6VYfAH-BzTfS-oBn5p-6VSg9f-tf7jxd-ekT8zf-dZgiep-6oBPr-fqForu-7SYi6u-33pVp4-vfN7Hk-ro6Sa-ro6RD-ro6S1-ro6Rr-ro6R7-rv8K-4rBkBu-4dHbpu-9P32zK-9P324g-9P31Ui-9P5RCy-3Fb7Fg-nCLD2g-CEN9-fqr8nz-5415XQ-njv1J9-33pVU4-33pVNZ-33utLE-33utCq-33utnf-33utg3-33ut8u-33pUWp-33pUP4-33pUCa-33usD7-rC16-rC17

**Comment by DeckOfPandas** [comment]
We've ahd a bunch of gorgeous images custom-sized by Paul Clarke, so will close this one.
