### ISSUE TITLE
Images aren't optimised/progressive

### ISSUE THREAD

**Issue by DeckOfPandas** [nhshackday/nhshackday.github.io#178]
A la https://optimus.io/support/progressive-jpeg/

(Thanks @simon-og )

**Comment by simon-og** [comment]
I don't actually know if progressive is good these days. 
http://www.webperformancetoday.com/2014/09/17/progressive-image-rendering-good-evil/

Maybe just do the magical 50% lossless compression google suggests!
https://github.com/nhshackday/nhshackday.github.io/issues/179

**Comment by blu3id** [comment]
Probably/mostly addressed by #236
