### ISSUE TITLE
Make sure a sensible amount of each header photo is shown

### ISSUE THREAD

**Issue by DeckOfPandas** [nhshackday/nhshackday.github.io#224]
e.g.
![screen shot 2018-01-18 at 14 58 28](https://user-images.githubusercontent.com/2399432/35104209-16e1d1d6-fc60-11e7-9e0a-fbfa44f453d8.png)

![screen shot 2018-01-18 at 14 58 37](https://user-images.githubusercontent.com/2399432/35104211-18b31722-fc60-11e7-9832-b14495da13ce.png)

**Comment by blu3id** [comment]
Partially addressed by #236 some of the featured projects headers don't quite fit but these egregious examples have been dealt with.
